Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "55.55.55.5" 

    config.vm.define "trusty" do |node|    
        node.vm.hostname = "trusty.local"
        node.vm.provision "ansible" do |ansible|        
            ansible.playbook = "main.yml"
    end
  end
end

# config.vm.provision "shell", inline: <<-SHELL
#        apt-get update
       
#    SHELL